app/website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.website.models import Events, User
from app.website.forms import EventForm, LoginForm
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin, login_user, LoginManager, login_required, current_user, logout_user
from app.website import db
from sqlalchemy import or_

# Create main blueprint
mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def home():
    events = Events.query.all()
    return render_template('index.html', event=events)


@mainbp.route('/event')
def events():
    events = Events.query.all()
    return render_template('events.html', all_events=events)

@mainbp.route('/show-event')
def single_event():
    return render_template('events-single.html')


@mainbp.route('/about')
def about():
    return render_template('about.html')


@mainbp.route('/contact')
def contact():
    return render_template('contact.html')



# ---------------------------- ADMIN -------------------------------------#


@mainbp.route('/login', methods=['GET', 'POST'])
def login():
    user_login = LoginForm()

    if user_login.validate_on_submit():
        user_name = user_login.name.data.lower()
        user = User.query.filter_by(name=user_name).first()

        if user is not None:
            if check_password_hash(user.password, user_login.password.data):
                login_user(user)

                return redirect(url_for("main.admin"))
            else:
                flash("Password incorrect, please try again.")
        else:
            flash("The user does not exist, please try again.")

    return render_template("login.html", form=user_login, logged_in=current_user.is_authenticated)

@mainbp.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():
    event_form = EventForm()


    if event_form.validate_on_submit():
        new_event = Events(
            name = event_form.name.data,
            description = event_form.description.data,
            date = event_form.date.data,
            time = event_form.time.data,
            location = event_form.location.data
        )

        db.session.add(new_event)
        db.session.commit()
        

        return redirect(url_for("main.all_post"))
    
    return render_template('admin.html', form=event_form)


@mainbp.route('/admin/all-post')
def all_post():
    events = Events.query.all()

    return render_template('admin-events.html', all_events=events)


@mainbp.route("/admin/delete/<int:event_id>")
@login_required
def delete_post(event_id):
    event_to_delete = Events.query.get(event_id)
    Events.query.filter(Events.id == event_id).delete()
    db.session.delete(event_to_delete)
    db.session.commit()
    return redirect(url_for('main.all_post'))


@mainbp.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You have successfully logged out!", 'success')
    return redirect(url_for('main.login'))

app/website/templates/admin-events.html
{% import "bootstrap/wtf.html" as wtf %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Include Bootstrap CSS from a CDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css">
    <title>TNCBC Admin</title>
    <!-- <link rel="stylesheet" href="/static/css/styles.css"> -->

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <a class="button"
    href="{{url_for('main.logout')}}"
    class="btn btn-outline-light btn-sm-block btn-login"
    >Logout</a>
    <div class="container mt-5">
        <!-- <form>
            <div class="mb-3">
                <label for="name" class="form-label">Name:</label>
                <input type="text" class="form-control" id="name" placeholder="Enter your name" required>
            </div>
            <div class="mb-3">
                <label for="description" class="form-label">Description:</label>
                <textarea class="form-control" id="description" placeholder="Enter a description" rows="4" required></textarea>
            </div>
            <div class="mb-3">
                <label for="date" class="form-label">Date:</label>
                <input type="date" class="form-control" id="date" required>
            </div>
            <div class="mb-3">
                <label for="time" class="form-label">Time:</label>
                <input type="time" class="form-control" id="time" required>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form> -->

        <div class="row wide block-large-1-2 block-900-full events-list">
            {% for event in all_events %}
            <div class="column events-list__item">

                <h3 class="display-1 events-list__item-title">
                    {{event.name}}
                </h3>
                <p>
               {{event.description}}
                </p>
                <ul class="events-list__meta">
                    <li class="events-list__meta-date">{{event.date.strftime("%A, %B %d, %Y")}}</li>
                    <li class="events-list__meta-time">{{event.time.strftime("%I:%M%p")}}</li>
                    <li class="events-list__meta-location">{{event.location}}</li>
                </ul>
                <a href="{{url_for('main.delete_post', event_id=event.id) }}">✘</a>
            </div>
            {% endfor %}


    </div>
</body>

</html>

app/website/templates/contact.html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>TNCBC Agege - Contact</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="/static/css/vendor.css">
    <link rel="stylesheet" href="/static/css/main.css">

    <!-- script
    ================================================== -->
    <script src="js/modernizr.js"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
    <link rel="manifest" href="site.webmanifest">

</head>

<body id="top">

    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader" class="dots-jump">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>


    <!-- header
    ================================================== -->
    <header class="s-header">

        <div class="header-logo">
            <a class="site-logo" href="{{ url_for('main.home') }}">
                <img src="../static/images/logo.png" alt="Homepage">
            </a>
        </div>

        <nav class="header-nav-wrap">
            <ul class="header-nav">
                <li><a href="{{ url_for('main.home') }}" title="Home">Home</a></li>
                <li><a href="{{ url_for('main.about') }}" title="About">About</a></li>
                <li><a href="{{ url_for('main.events') }}" title="Services">Events</a></li>
                <li class="current"><a href="{{ url_for('main.contact') }}" title="Contact us">Contact</a></li>	
            </ul>
        </nav>

        <a class="header-menu-toggle" href="#0"><span>Menu</span></a>

    </header> <!-- end s-header -->


    <!-- page header
    ================================================== -->
    <section class="page-header page-header--contact">

        <div class="gradient-overlay"></div>
        <div class="row page-header__content">
            <div class="column">
                <h1>Contact Us</h1>
            </div>
        </div>

    </section> <!-- end page-header -->


    <!-- page content
    ================================================== -->
    <section class="page-content">

        <div class="row">
            <div class="column">

                <p class="lead drop-cap">
                Corrupti voluptas sed possimus odio cupiditate. Ut id nemo doloremque 
                iusto voluptates placeat esse ut. Voluptatem saepe aut vel ut. Perferendis 
                hic voluptates quibusdam animi quis est itaque. Atque delectus praesentium 
                voluptas voluptas. Odio voluptatem facilis magni magnam quas aut quasi.                 
                </p>

                <p>
                Nam est quae harum doloribus illum consequatur cupiditate quod rem. Error 
                qui culpa. Porro cupiditate veniam assumenda nostrum eius. Tempore rerum eos.
                Est perferendis nesciunt corrupti quia sunt reprehenderit id autem. 
                Quis in voluptates perspiciatis. Voluptatem saepe aut vel ut reprehenderit id
                perferendis.
                </p>

                <div class="row">
                    <div class="column large-6 tab-full">
                        <h3>Main Office.</h3>
                        <p>
                        1600 Amphitheatre Parkway<br>
                        Mountain View, CA 94043 US<br>
                        Mon-Thur 8:30am – 4:30pm 
                        </p>
                    </div>

                    <div class="column large-6 tab-full">
                        <h3>Contact Info.</h3>
                        <p>
                        sayhello@hesed.com<br>
                        info@hesed.com <br>
                        Phone: +197 543 2345
                        </p>
                    </div>
                </div>


                <h2>Get In Touched.</h2>

                <form name="contactForm" id="contactForm" method="post" action="" autocomplete="off">
                    <fieldset>

                        <div class="form-field">
                            <input name="cName" id="cName" class="h-full-width h-remove-bottom" placeholder="Your Name" value="" type="text">
                        </div>

                        <div class="form-field">
                            <input name="cEmail" id="cEmail" class="h-full-width h-remove-bottom" placeholder="Your Email" value="" type="text">
                        </div>

                        <div class="form-field">
                            <input name="cWebsite" id="cWebsite" class="h-full-width h-remove-bottom" placeholder="Website" value="" type="text">
                        </div>

                        <div class="message form-field">
                            <textarea name="cMessage" id="cMessage" class="h-full-width h-remove-bottom" placeholder="Your Message"></textarea>
                        </div>

                        <br>

                        <input name="submit" id="submit" class="btn btn--primary btn-wide btn--large h-full-width" value="Send Message" type="submit">

                    </fieldset>
                </form>

            </div>
        </div>

    </section> <!-- end page-content -->


    <!-- Social
    ================================================== -->
    <section class="s-social">
            
        <div class="row social-content">
            <div class="column">
                <ul class="social-list">
                    <li class="social-list__item">
                        <a href="#0" title="">
                            <span class="social-list__icon social-list__icon--facebook"></span>
                            <span class="social-list__text">Facebook</span>
                        </a>
                    </li>
                    <li class="social-list__item">
                        <a href="#0" title="">
                            <span class="social-list__icon social-list__icon--twitter"></span>
                            <span class="social-list__text">Twitter</span>
                        </a>
                    </li>
                    <li class="social-list__item">
                        <a href="#0" title="">
                            <span class="social-list__icon social-list__icon--instagram"></span>
                            <span class="social-list__text">Instagram</span>
                        </a>
                    </li>
                    <li class="social-list__item">
                        <a href="#0" title="">
                            <span class="social-list__icon social-list__icon--email"></span>
                            <span class="social-list__text">Email</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div> <!-- end social-content -->

    </section> <!-- end s-social -->


    <!-- footer
    ================================================== -->
    <footer class="s-footer">

        <div class="row footer-top">
            <div class="column large-4 medium-5 tab-full">
                <div class="footer-logo">
                    <a class="site-footer-logo" href="index.html">
                        <img src="images/logo.svg" alt="Homepage">
                    </a>
                </div>  <!-- footer-logo -->
                <p>
                Laborum ad explicabo. Molestiae voluptates est. Quisquam labore tenetur 
                et assumenda voluptatibus a beatae. Rerum odio ducimus reprehenderit 
                sit animi laborum nostrum dolorum animi voluptates est voluptatibus a beatae. 
                </p>
            </div>
            <div class="column large-half tab-full">
                <div class="row">
                    <div class="column large-7 medium-full">
                        <h4 class="h6">Our Location</h4>
                        <p>
                        1600 Amphitheatre Parkway <br>
                        Mountain View, California <br>
                        94043 US
                        </p>
        
                        <p>
                        <a href="https://goo.gl/maps/bc7C7eYtSmnNs6216" target="_blank" class="btn btn--footer">Get Direction</a>
                        </p>
                    </div>
                    <div class="column large-5 medium-full">
                        <h4 class="h6">Quick Links</h4>
                        <ul class="footer-list">
                            <li><a href="index.html">Home</a></li>
                            <li><a href="about.html">About</a></li>
                            <li><a href="volunteer.html">Volunteer</a></li>
                            <li><a href="connect-group.html">Connect Groups</a></li>
                            <li><a href="events.html">Upcoming Events</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> <!-- end footer-top -->

        <div class="row footer-bottom">
            <div class="column ss-copyright">
                <span>© Copyright Hesed 2019</span> 
                <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
            </div>
        </div> <!-- footer-bottom -->

        <div class="ss-go-top">
            <a class="smoothscroll" title="Back to Top" href="#top">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0l8 9h-6v15h-4v-15h-6z"/></svg>
            </a>
        </div> <!-- ss-go-top -->

    </footer> <!-- end s-footer -->


    <!-- Java Script
    ================================================== -->
    <script src="{{ url_for('static', filename='js/modernizr.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>

app/website/templates/index.html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>TNCBC Agege | Lagos</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="/static/css/main.css">

    <!-- script
    ================================================== -->
    <script src="js/modernizr.js"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
    <link rel="manifest" href="site.webmanifest">

</head>

<body id="top">

    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader" class="dots-jump">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>


    <!-- header
    ================================================== -->
    <header class="s-header">

        <div class="header-logo">
            <a class="site-logo" href="{{ url_for('main.home') }}">
                <img src="../static/images/logo.png" alt="Homepage">
            </a>
        </div>

        <nav class="header-nav-wrap">
            <ul class="header-nav">
                <li class="current"><a href="{{ url_for('main.home') }}" title="Home">Home</a></li>
                <li><a href="{{ url_for('main.about') }}" title="About">About</a></li>
                <li><a href="{{ url_for('main.events') }}" title="Services">Events</a></li>
                <li><a href="{{ url_for('main.contact') }}" title="Contact us">Contact</a></li>	
            </ul>
        </nav>

        <a class="header-menu-toggle" href="#0"><span>Menu</span></a>

    </header> <!-- end s-header -->


    <!-- hero
    ================================================== -->
    <section class="s-hero" data-parallax="scroll" data-image-src="../static/images/IMG_2737 - Copy.JPG" data-natural-width=3000 data-natural-height=2000 data-position-y=center>

        <div class="hero-left-bar"></div>

        <div class="row hero-content">

            <div class="column large-full hero-content__text">
                <h1>
                    Christ in you <br>
                    The Hope of Glory <br>
                    Col 1:27
                </h1>

                <div class="hero-content__buttons">
                    <a href="{{ url_for('main.events') }}" class="btn btn--stroke">Upcoming Events</a>
                    <a href="{{ url_for('main.about') }}" class="btn btn--stroke">About Us</a>
                </div>
            </div> <!-- end hero-content__text -->

        </div> <!-- end hero-content -->

        <ul class="hero-social">
            <li class="hero-social__title">Follow Us</li>
            <li>
                <a href="https://www.facebook.com/TNCBCMEDIA" title="">Facebook</a>
            </li>
            <li>
                <a href="https://www.youtube.com/@TNCBCTV" title="">YouTube</a>
            </li>
            <li>
                <a href="https://www.instagram.com/tncbcagege/" title="">Instagram</a>
            </li>
        </ul> <!-- end hero-social -->

        <div class="hero-scroll">
            <a href="#about" class="scroll-link smoothscroll">
                Scroll For More
            </a>
        </div> <!-- end hero-scroll -->

    </section> <!-- end s-hero -->


    <!-- about
    ================================================== -->
    <section id="about" class="s-about">

        <div class="row row-y-center about-content">

            <div class="column large-half medium-full">
                <h3 class="subhead">Welcome to The New Covenant Baptist Church</h3>
                <p class="lead" style="text-align: justify;">
                The New Covenant Baptist Church, Agege (TNCBC), is a divine planting— a wholly righteous seed sown,
                nurtured, and pruned by the hand of God. Since its inception, our journey has been marked by God's unmistakable
                favor and grace, with fruitfulness that reflects His promise:
                    <br><p><i>a cloud of dew in the heat of harvest” (Isaiah 18:4)</i></p></br>
                </p>
                <a href="{{ url_for('main.about') }}" class="btn btn--primary btn--about">More About TNCBC Agege</a>
            </div>

            <div class="column large-half medium-full">
                <ul class="about-sched">
                    <li>
                        <h4>Main Church Service</h4>
                        <p>
                        First Service (Youthful Service) - 07:30 AM - 09:00 AM <br>
                        Sunday School - 09:00 AM - 10:00 AM <br>
                        Second Service - 10:00 AM - 12:00 PM <br>
                        </p>
                    </li>
                    <li>
                        <h4>Children's Service</h4>
                        <p>
                        Sunday - 10:00 AM - 12:00 PM <br>
                        </p>
                    </li>
                    <li>
                        <h4>Mid-week Service</h4>
                        <p>
                        Healing Dew (Tuesdays) - 07:00 AM - 08:00 AM <br>
                        Bible Study/Prayer Meeting (Wednesdays) - 06:00 PM - 07:30 PM <br>
                        </p>
                    </li>
                </ul> <!-- end about-sched-->
            </div>

        </div> <!-- end about-content -->

    </section> <!-- end s-about -->


    <!-- connect
    ================================================== -->
    <section class="s-connect">

        <div class="row connect-content">
            <div class="column large-half tab-full">
                <h3 class="display-1">Mission</h3>
                <p style="text-align: justify">
               “Go ye therefore and make disciples of all nations, baptizing them in the name of the Father and of the
                Son and of the Holy Spirit, teaching them to observe all that I have commanded you” <i>Matthew 28:19-20b</i>
                </p>
            </div>
            <div class="column large-half tab-full">
                <h3 class="display-1">Vision</h3>
                <p style="text-align: justify">
                A model Church committed to seeking the lost, incorporating them into a vibrant fellowship, building them
                into Christ-like character and nurturing them into fruitful service so as to glorify God
                </p>
            </div>
        </div> <!-- end connect-content  -->

    </section> <!-- end s-connect -->


    <!-- series
    ================================================== -->
    <section class="s-series">

        <div class="series-img" style="background-image: url('images/series-2000.jpg');"></div>

        <div class="row row-y-center series-content">

            <div class="column large-half medium-full">
                <h3 class="subhead">Current Series</h3>
                <h2>Shape Your Life with the Words of Life.</h2>
                <p>
                Aut sed amet et quis aliquid laborum minus consequatur. Animi repellendus quas. 
                Est voluptates minima ut dolorum aliquid sint. Ratione et et molestias rerum 
                quibusdam. Deserunt suscipit ut expedita. Non numquam aut eum perferendis 
                molestiae praesentium aliquid voluptatum numquam dolorum aliquid sint minima.
                </p>
            </div> <!-- end column -->

            <div class="column large-half medium-full">
                <div class="series-content__buttons">
                    <a href="" class="btn btn--large h-full-width">Watch the Video</a>
                    <a href="" class="btn btn--large h-full-width">Listen To the Message</a>
                </div>

                <div class="series-content__subscribe">
                    <p>
                    Never missed a message. Subscribe to our YouTube and Podcast channels.
                    </p>
                    
                    <ul class="series-content__subscribe-links">
                        <li class="ss-apple-podcast"><a href="#0">Apple Podcast</a></li>
                        <li class="ss-spotify"><a href="#0">Spotify</a></li>
                        <li class="ss-soundcloud"><a href="#0">SoundCloud</a></li>
                        <li class="ss-youtube"><a href="#0">Youtube</a></li>
                    </ul>
                </div>
            </div> <!-- end column -->
            
        </div> <!-- series-content -->

    </section> <!-- end s-series -->


    <!-- Social
    ================================================== -->
    <section class="s-social">
            
        <div class="row social-content">
            <div class="column">
                <ul class="social-list">
                    <li class="social-list__item">
                        <a href="https://www.facebook.com/TNCBCMEDIA" title="">
                            <span class="social-list__icon social-list__icon--facebook"></span>
                            <span class="social-list__text">Facebook</span>
                        </a>
                    </li>
                    <li class="social-list__item">
                        <a href="https://x.com/TNCBCAgege" title="">
                            <span class="social-list__icon social-list__icon--twitter"></span>
                            <span class="social-list__text">Twitter</span>
                        </a>
                    </li>
                    <li class="social-list__item">
                        <a href="https://www.instagram.com/tncbcagegelagos/" title="">
                            <span class="social-list__icon social-list__icon--instagram"></span>
                            <span class="social-list__text">Instagram</span>
                        </a>
                    </li>
                    <!-- <li class="social-list__item">

                        <a href="tncbctv@gmail.com" title="">
                            <span class="social-list__icon social-list__icon--email"></span>
                            <span class="social-list__text">Email</span>
                        </a>
                    </li> -->
                </ul>
            </div>
        </div> <!-- end social-content -->

    </section> <!-- end s-social -->


    <!-- footer
    ================================================== -->
    <footer class="s-footer">

        <div class="row footer-top">
            <div class="column large-4 medium-5 tab-full">
                <div class="footer-logo">
                    <a class="site-footer-logo" href="index.html">
                        <img src="../static/images/logo.png" alt="Homepage">
                    </a>
                </div>  <!-- footer-logo -->
                <p style="text-align: justify">
                    The New Covenant Baptist Church, Agege (TNCBC), is a divine planting— a wholly righteous seed sown,
                    nurtured and pruned by the hand of God.
                </p>
            </div>
            <div class="column large-half tab-full">
                <div class="row">
                    <div class="column large-7 medium-full">
                        <h4 class="h6">Our Location</h4>
                        <p>
                        The New Covenant Baptist Church,<br>
                        Agege, Lagos, Ijaiye Low-Cost Housing Estate,<br>
                        Ogba Rd, Lagos
                        </p>
        
                        <p>
                        <a href="https://maps.app.goo.gl/j3Kas3yQrZS6qB686" target="_blank" class="btn btn--footer">Get Direction</a>
                        </p>
                    </div>
                    <div class="column large-5 medium-full">
                        <h4 class="h6">Quick Links</h4>
                        <ul class="footer-list">
                            <li><a href="index.html">Home</a></li>
                            <li><a href="about.html">About</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> <!-- end footer-top -->

        <div class="row footer-bottom">
            <div class="column ss-copyright">
                <span>© Copyright</span>
                <span>Design by <a href="https://www.styleshout.com/">TNCBC Agege Media</a></span>
            </div>
        </div> <!-- footer-bottom -->

        <div class="ss-go-top">
            <a class="smoothscroll" title="Back to Top" href="#top">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0l8 9h-6v15h-4v-15h-6z"/></svg>
            </a>
        </div> <!-- ss-go-top -->

    </footer> <!-- end s-footer -->


    <!-- Java Script
    ================================================== -->
    <script src="{{ url_for('static', filename='js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>

app/website/templates/login.html
{% import "bootstrap/wtf.html" as wtf %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <!-- Add Bootstrap CSS link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Add your custom CSS link -->
    <link rel="stylesheet" href="/static/css/styles.css">
</head>
<body>
    <div class="container login-container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h4>Login</h4>
                    </div>
                    <div class="card-body">
                        {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for message in messages %}
                                <p>{{ message }}</p>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}

                    {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "primary"}) }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Add Bootstrap JS scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>